### ISSUE TITLE
'Elapsed' Info Accumulates

### ISSUE THREAD

**Issue by o2cr** [anned20/vimsence#2]
Elapsed information in Discord seems to be accumulating instead of resetting every time you open a file with vim.

![image](https://user-images.githubusercontent.com/5484761/46735656-70eeef80-ccc9-11e8-9295-478d600bfe51.png)

Quitting vim, followed by opening a new file will still continue the elapsed time.

![image](https://user-images.githubusercontent.com/5484761/46735861-0d18f680-ccca-11e8-991c-67246088a1fb.png)

Using a vanilla `.vimrc`, `vim-plug` and only this plugin loaded will still cause the issue. The accumulated time still appears even after a reboot.

EDIT : It seems that according to Discord `startTimestamp` uses an integer, and Python's `time()` outputs as a float. Rounding off like `start_time = round(time.time())` actually did the trick. I'm not sure whether other people are experiencing this but I just submitted a pull request just in case.

**Comment by anned20** [comment]
This seems particularly odd, but I tested it and it seems to work. I'll merge it because it doesn't break anything and seems to fix this.

Thanks for your contribution!
