### ISSUE TITLE
No game icon

### ISSUE THREAD

**Issue by ghost** [anned20/vimsence#4]
There is no game icon in Rich Presence, unlike in any other game.
![image](https://user-images.githubusercontent.com/31247845/55633872-51470880-57ce-11e9-969c-7cef3c5792ee.png)

**Comment by hugolgst** [comment]
Could you add an Icon like an question mark when vimsence don't recognize the language ?

**Comment by ghost** [comment]
@ananagame that's possible, but as far as I know, you will either have to create your own Discord app then add your own icons, or either wait until repo owner will do that (maybe they even won't).

If you want to add your own icons by yourself (and just for yourself, as you're editing in a local repo), then:
1. go to [Discord app dashboard](https://discordapp.com/developers/applications), create new Discord app (name it whatever), then create assets with names as specified in [script](https://github.com/anned20/vimsence/blob/be6d8a259f713eb4233901c69f3f2184a020133f/python/vimsence.py#L12):

2. [Change](https://github.com/anned20/vimsence/blob/be6d8a259f713eb4233901c69f3f2184a020133f/python/vimsence.py#L20) `client_id` to your Discord app's client ID.

3. [Edit the script](https://github.com/anned20/vimsence/blob/be6d8a259f713eb4233901c69f3f2184a020133f/python/vimsence.py#L37) so it won't just pass if `get_extension()` is `None` (just a brief example):
```python
if get_extension():
        activity['assets']['large_image'] = get_extension()
else:
        activity['assets']['large_image'] = 'unknown_type' # Name of your defined 'unknown type' asset in Discord application```

**Comment by hugolgst** [comment]
Sure but the best would be an update by the owner

**Comment by ghost** [comment]
> Sure but the best would be an update by the owner

Well, I'm pretty sure they'll never even respond to this issue...
Besides, I would even create PR, but it's theirs Discord application, and I have no access to it.

**Comment by hugolgst** [comment]
That's great thanks ! :)
