### ISSUE TITLE
Error during the installation

### ISSUE THREAD

**Issue by tmpaccount01** [anned20/vimsence#7]
Hello,

I tried to install this plugin but its failed when i make :BundleInstall :

Error found while processing /home/cry/.vim/bundle/vimsence/plugin/vimsence.vim:
line 20:
closing connection

**Comment by ghost** [comment]
I've had the same issue, but yet the only thing I can suggest is using this fork - https://github.com/ananagame/vimsence

**Comment by tmpaccount01** [comment]
Hi,
I also tried with this fork and i had the same issue

**Comment by hughesjs** [comment]
I am also having this issue, I've checked and my vim appears to have been configured with `+python/dyn` support

**Comment by tmpaccount01** [comment]
> I am also having this issue, I've checked and my vim appears to have been configured with `+python/dyn` support

Did u solve this ?

**Comment by hughesjs** [comment]
Nope, I've had no luck.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by RossComputerGuy** [comment]
This bug randomly started happening for no reason, I've had it for months. I think the Discord dev app was changed and the vim plugin wasnt fixed.

**Comment by tmpaccount01** [comment]
Hi RossComputerGuy, try to use this fork  https://github.com/ananagame/vimsence. It worked for me.

gl

**Comment by tmpaccount01** [comment]
.
