### ISSUE TITLE
Installation not friendly for beginners

### ISSUE THREAD

**Issue by ghost** [anned20/vimsence#9]
Hi,

I'm on Mac and I am a beginner. The installation is kind of confusing for me please add screenshots of how you install.

Thanks.

**Comment by Axarva** [comment]
> Hi,
> 
> I'm on Mac and I am a beginner. The installation is kind of confusing for me please add screenshots of how you install.
> 
> Thanks.

Do you have Vim-plug or such a plugin? If not, go through installing vim-plug first
After that, edit the .vimrc file in your home directory to include the lines in the README of this project. Save the file, launch vim, and then type in the editor command ‘:PlugInstall’
(An editor command is like :q which exits vim if you remember)
This will install it for you and hence you can use it. 
I’m pretty sure that’s the same for all OSes with vim.

**Comment by anned20** [comment]
Sorry for the delayed reaction, but what @Axarva said above applies. It's just a simple Vim plugin, works just like any other Vim plugin.
